package App;

import java.util.ArrayList;
import Backend.BookBackend;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tgbrk
 */
public class LibrarianAdd extends javax.swing.JFrame {

    DefaultTableModel model;
    
    /**
     * Creates new form Librarian
     */
    public LibrarianAdd() {
        initComponents();
        model = (DefaultTableModel) tblBooks.getModel();
        fillTable();
    }
    
    private void fillTable(){
        ArrayList<Object[]> books = new BookBackend().retrieveAllBooks();
        for(Object[] book : books){
            model.insertRow(tblBooks.getRowCount(), book);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        txtAuthor = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Collection");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBooks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Name", "Author", "Genre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBooks.setShowGrid(true);
        tblBooks.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(tblBooks);
        tblBooks.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 59, 443, 260));

        txtAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 123, 156, -1));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 172, 156, -1));

        txtGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenreActionPerformed(evt);
            }
        });
        jPanel1.add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 221, 156, -1));

        lblName.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblName.setText("Name:");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 163, 162, -1));

        lblGenre.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblGenre.setText("Genre:");
        jPanel1.add(lblGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 212, 192, -1));

        lblAuthor.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblAuthor.setText("Author:");
        jPanel1.add(lblAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 114, 106, -1));

        btnBack.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 19, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tgbrk\\OneDrive\\Pictures\\res 7.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1310, 640));

        btnRemove.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnRemove.setText("Remove Book");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 228, -1));

        btnAdd.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnAdd.setText("Add Book");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 230, -1));

        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btnUpdate.setText("Update Book");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 500, 212, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 1313, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenreActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtGenreActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel model = (DefaultTableModel)tblBooks.getModel();
        if(txtName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Enter book name");
            txtName.grabFocus();
            return;
        }
        if(txtAuthor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Enter Author name");
            txtAuthor.grabFocus();
            return;
        }
        if(txtGenre.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Enter the genre");
            txtGenre.grabFocus();
            return;
        }
        model.addRow(new Object[]{
            tblBooks.getRowCount()+1,
            txtName.getText(),
            txtAuthor.getText(),
            txtGenre.getText()
        });
        int status = new BookBackend().addBook(txtName.getText(), txtAuthor.getText(), txtGenre.getText());
        txtAuthor.setText("");
        txtGenre.setText("");
        //txtID.setText("");
        txtName.setText("");
        if(status == 0){
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Failed to add new book");
        }else{
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Book added to the Library");
        }
         
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
      DefaultTableModel model=(DefaultTableModel)tblBooks.getModel();
      int SelectedRowIndex=tblBooks.getSelectedRow();
      if(SelectedRowIndex == -1){
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Select a row to update");
            return;
      }
      try{
      
        String ID=model.getValueAt(SelectedRowIndex, 0).toString();
        String Nam=model.getValueAt(SelectedRowIndex, 1).toString();
        String Auth=model.getValueAt(SelectedRowIndex, 2).toString();
        String Gen=model.getValueAt(SelectedRowIndex, 3).toString();
      
        String newName=JOptionPane.showInputDialog(null, "Enter the Name of Book",Nam);
        String newAuthor=JOptionPane.showInputDialog(null, "Enter the Author",Auth);
        String newGenre=JOptionPane.showInputDialog(null, "Enter the Genre",Gen);
        
            
        //model.setValueAt(newId,SelectedRowIndex,0);
        model.setValueAt(newName,SelectedRowIndex,1);
        model.setValueAt(newAuthor,SelectedRowIndex,2);
        model.setValueAt(newGenre,SelectedRowIndex,3);
        int status = new BookBackend().updateBook(Integer.parseInt(ID), newName, newAuthor, newGenre);
        if(status == 1)
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Updated successfully");
        else
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Updation failed");
            
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(LibrarianAdd.this,"No Row Selected"+e.getMessage());
      }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAuthorActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtAuthorActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNameActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model= (DefaultTableModel) tblBooks.getModel();
        //get selected row index
        int SelectedRowIndex=tblBooks.getSelectedRow();
        if(SelectedRowIndex == -1)
            JOptionPane.showMessageDialog(LibrarianAdd.this, "Select a row to delete");
        else
            model.removeRow(SelectedRowIndex);
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new LibrarianDashboard("").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        tblBooks.clearSelection();
    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
