/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import Backend.PasswordChecker;
import Backend.FineBackend;
import javax.swing.JOptionPane;
import java.awt.Cursor;

/**
 *
 * @author lenovo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        new FineBackend().refreshFines();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblRegister = new javax.swing.JLabel();
        lblAccountType = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        cbShowPass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Management System");
        setMinimumSize(new java.awt.Dimension(640, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        lblLogin.setText("Login");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 39, -1, -1));

        lblUserName.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblUserName.setText("Enter User Name: ");
        getContentPane().add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 222, -1, -1));

        lblPassword.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblPassword.setText("Enter Password: ");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 284, 227, -1));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 224, 243, -1));

        pwdPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 286, 243, -1));

        btnLogin.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 386, -1, -1));

        lblRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegister.setText("New user? Register here");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterMouseEntered(evt);
            }
        });
        getContentPane().add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 441, -1, -1));

        lblAccountType.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        lblAccountType.setText("Account Type:");
        getContentPane().add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 166, 227, -1));

        cmbUserType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select>", "Customer", "Librarian" }));
        cmbUserType.setToolTipText("Select the type of user");
        getContentPane().add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 168, 180, -1));

        cbShowPass.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        cbShowPass.setText("Show Password");
        cbShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowPassActionPerformed(evt);
            }
        });
        getContentPane().add(cbShowPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 335, 205, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tgbrk\\Downloads\\—Pngtree—library cartoon banner illustration_1065759.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1280, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void loginHandler(){
        
        if(cmbUserType.getSelectedItem().equals("Customer")){
            int status = new PasswordChecker().verifyLoginDetails(txtUserName.getText().trim(), pwdPassword.getText(), (String)cmbUserType.getSelectedItem());
            if(status == -1){
                    JOptionPane.showMessageDialog(Login.this, "Invalid Credentials");
                    return;
            }
            CustomerDashboard cd = new CustomerDashboard(txtUserName.getText().trim());
            cd.setVisible(true);
            this.dispose();
        }
        else{
            int status = new PasswordChecker().verifyLoginDetails(txtUserName.getText().trim(), pwdPassword.getText(), (String)cmbUserType.getSelectedItem());
            if(status == -1){
                    JOptionPane.showMessageDialog(Login.this, "Invalid Credentials");
                    return;
            }
            LibrarianDashboard ld = new LibrarianDashboard(txtUserName.getText().trim());
            ld.setVisible(true);
            this.dispose();
        }
    }
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(cmbUserType.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(Login.this, "Select an account type");
            cmbUserType.grabFocus();
        }
        else if(txtUserName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(Login.this, "Enter a valid user name");
            txtUserName.grabFocus();
        }
        else if(pwdPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(Login.this, "Enter a valid password");
            pwdPassword.grabFocus();
        }
        else{
            loginHandler();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseEntered
        lblRegister.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblRegisterMouseEntered

    private void cbShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowPassActionPerformed
        if(cbShowPass.isSelected()){
            pwdPassword.setEchoChar('\u0000');
        }else{
            pwdPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_cbShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbShowPass;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
